{
 "title": "jmeter Дефолтные графики",
 "description": "Dashboard for Jmeter using Backend listener and InfluxDB.",
 "tags": [ "load_test" ],
 "time": { "from": "2025-10-08T14:16:28.124Z", "to": "2025-10-09T07:43:40.073Z" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "data_source", "query": "influxdb" },
   {
    "name": "application",
    "label": "application",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   {
    "name": "transaction",
    "label": "transaction",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"transaction\" WHERE \"application\" =~ /^$application$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all' AND $timeFilter"
   },
   {
    "name": "UID",
    "query": "a612dc52-1277-4242-a2d9-bcfb19fbf09f"
   },
   { "name": "dashboardName", "query": "jmeter-dashboard-influxdb" },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1s,10s,30s,1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Response Time Distribution in table - Pass (95th pct)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT sum(\"count\") AS \"0-500 ms\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" <= 500\nGROUP BY \"transaction\""
    },
    {
     "query": "SELECT sum(\"count\") AS \"500-1000 ms\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 500 AND \"pct95.0\" <= 1000\nGROUP BY \"transaction\""
    },
    {
     "query": "SELECT sum(\"count\") AS \"1000-3000MS\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~/^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 1000 AND \"pct95.0\" <= 3000\nGROUP BY \"transaction\""
    },
    {
     "query": "SELECT sum(\"count\") AS \"3000-5000 ms\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~/^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 3000 AND \"pct95.0\" <= 5000\nGROUP BY \"transaction\""
    },
    {
     "query": "SELECT sum(\"count\") AS \"5000-10000 ms\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 5000 AND \"pct95.0\" <= 10000\nGROUP BY \"transaction\""
    },
    {
     "query": "SELECT sum(\"count\") AS \"10000+ ms\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 10000\nGROUP BY \"transaction\""
    }
   ]
  },
  {
   "title": "Response Time Distribution - Pass (95th pct)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "0-500 ms",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" <= 500"
    },
    {
     "alias": "500-1000 ms",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 500 AND \"pct95.0\" <= 1000"
    },
    {
     "alias": "1000-3000 ms",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 1000 AND \"pct95.0\" <= 3000"
    },
    {
     "alias": "3000-5000 ms",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 3000 AND \"pct95.0\" <= 5000"
    },
    {
     "alias": "5000-10000 ms",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 5000 AND \"pct95.0\" <= 10000"
    },
    {
     "alias": "10000+ ms",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter AND \"pct95.0\" > 10000"
    }
   ]
  },
  {
   "title": "Тестовые графики сюда пока не смотреть",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connect",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT \"connectTime\" \nFROM \"requestsRaw\" \nWHERE $timeFilter\nLIMIT 10",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Times Destribution ",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "fast_responses",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT count(\"responseTime\") AS \"fast_responses\"\nFROM \"jmeter\"\nWHERE \"application\" =~ /^$application$/ \n  AND \"responseTime\" <= 1000 \n  AND $timeFilter",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "total_responses",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT count(\"responseTime\") AS \"total_responses\"\nFROM \"jmeter\"\nWHERE \"application\" =~ /^$application$/ \n  AND $timeFilter",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Latency",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SHOW FIELD KEYS FROM \"requestsRaw\"",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Latency",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "requestName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT mean(\"latency\")\nFROM \"autogen\".\"jmeter\"\nWHERE \"application\" =~ /^$application$/ \n  AND $timeFilter\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Times по HTTP* и \"statut\" = 'ok'",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Mean",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT mean(\"avg\")\nFROM \"jmeter\"\nWHERE (\"application\" =~ /^$application$/\nAND \"transaction\" =~ /^HTTP.*/ AND \"statut\" = 'ok')\n  AND $timeFilter\nGROUP BY time($aggregation)\nfill(null)",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "90 perc",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT mean(\"pct90.0\")\nFROM \"jmeter\"\nWHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^HTTP.*/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "99 perc",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT mean(\"pct99.0\")\nFROM \"jmeter\"\nWHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^HTTP.*/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         { "params": [ "90" ], "type": "percentile" }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT max(\"avg\")\nFROM \"jmeter\"\nWHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^HTTP.*/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Codes per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT count(\"count\")\nFROM \"autogen\".\"jmeter\"\nWHERE \"application\" =~ /^$application$/ AND \"transaction\" =~ /^HTTP.*/ AND $timeFilter GROUP BY time($aggregation), \"responseCode\"\nfill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "errorMessage", "operator": "=", "value": "Null" }
       ]
      }
     ]
    },
    {
     "title": "Average Response Times",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT mean(\"avg\")\nFROM \"autogen\".\"jmeter\"\nWHERE (\"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/ AND \"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Times Destribution, 90% percentile ",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_requestName",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "requestsRaw",
       "query": "SELECT percentile(\"responseTime\", 90) / 1000\nFROM \"jmeter\"\nWHERE \"application\" =~ /^$application$/ \n  AND $timeFilter\nGROUP BY \"requestName\"",
       "select": [
        [
         { "params": [ "responseTime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "requestName", "operator": "=~", "value": "/^$request$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Run Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Run Test",
     "type": "table",
     "description": "Таблица запущенных / завершенных тестов",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "tags" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "events",
       "query": "SELECT \"text\" FROM \"autogen\".\"events\" WHERE (\"text\" =~ /.* started/) AND $timeFilter GROUP BY \"tags\", \"application\"",
       "select": [
        [
         { "params": [ "text" ], "type": "field" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "text", "operator": "=~", "value": "/.* started/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "tags" ], "type": "tag" },
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "events",
       "query": "SELECT \"text\" FROM \"autogen\".\"events\" WHERE (\"text\" =~ /.* ended/) AND $timeFilter GROUP BY \"tags\", \"application\"",
       "select": [
        [
         { "params": [ "text" ], "type": "field" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "text", "operator": "=~", "value": "/.* ended/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Threads - Total Throughput (^HTTP.* - \"ok\")",
     "type": "timeseries",
     "description": "Активные потоки / Кол-во запросов в секунду",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "Threads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"maxAT\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "maxAT" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      },
      {
       "alias": "RPS",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok'  AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "maxAT" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Finished Threads",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "endedT" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Failed Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Total Error",
     "type": "timeseries",
     "description": "Кол-во ошибок",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Error Rate %",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "totalCount",
       "groupBy": [
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") AS \"totalReq\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY \"application\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "totalReq" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "totalCountError",
       "groupBy": [
        { "params": [ "application" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") AS \"totalFail\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY \"application\"",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ "totalFail" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Response Times по HTTP* и statut ok",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Average",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"avg\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /^HTTP.*/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "avg" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      },
      {
       "alias": "90th Percentage",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct90.0\")  FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /^HTTP.*/ AND  \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
       ]
      },
      {
       "alias": "95th Percentage",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct95.0\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /^HTTP.*/ AND  \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)\n",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "99th Percentage",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"pct99.0\")  FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /^HTTP.*/ AND  \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "pct99.0" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
       ]
      },
      {
       "alias": "Max",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT last(\"max\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /^HTTP.*/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "max" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RPS / Response Time по _UC*",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS - Pass",
     "type": "timeseries",
     "description": "Кол-во успешных запросов в секунду",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      },
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time - Pass (95th pct)",
     "type": "timeseries",
     "description": "Время выполнения успешных запросов (95thpct)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct95.0\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "RPS - 4xx",
     "type": "timeseries",
     "description": "Кол-во запросов в секунду с кодом ответа 4xx",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^_UC.*/ AND \"responseCode\" =~ /4../) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" }
       ]
      }
     ]
    },
    {
     "title": "RPS - Failed",
     "type": "timeseries",
     "description": "Кол-во неудачных запросов в секунду",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      },
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Error - Response Code",
     "type": "timeseries",
     "description": "Кол-во неудачных запросов по кодам",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "responseCode" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation), \"responseCode\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Time - Failed (95th pct)",
     "type": "timeseries",
     "description": "Время выполнения неудачных запросов (95thpct)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct95.0\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "RPS - 5xx",
     "type": "timeseries",
     "description": "Кол-во запросов в секунду с кодом ответа 5xx",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" =~ /5../ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      },
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^$request$/ AND \"responseCode\" =~ /5../ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
        { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" }
       ]
      }
     ]
    },
    {
     "title": "Pie - Error Response Code",
     "type": "piechart",
     "description": "Пирог с процентом ошибок по кодам",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_responseCode",
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"responseCode\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
        { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "RPS / Response Time по HTTP*", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RPS - Pass",
   "type": "timeseries",
   "description": "Кол-во успешных запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / 5 \nFROM \"autogen\".\"jmeter\" \nWHERE (\n  \"application\" =~ /^$application$/ \n  AND \"statut\" = 'ok' \n  AND \"transaction\" =~ /^HTTP.*/\n) \nAND $timeFilter \nGROUP BY time($aggregation), \"transaction\" \nfill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / 5 \nFROM \"autogen\".\"jmeter\" \nWHERE (\n  \"application\" =~ /^$application$/ \n  AND \"statut\" = 'ok' \n  AND \"transaction\" =~ /^HTTP.*/\n) \nAND $timeFilter \nGROUP BY time($aggregation) \nfill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time - Pass (95th pct)",
   "type": "timeseries",
   "description": "Время выполнения успешных запросов (95thpct)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS - 4xx",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду с кодом ответа 4xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" =~ /4../ AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"responseCode\" =~ /4../ AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/4../" }
     ]
    }
   ]
  },
  {
   "title": "RPS - Failed",
   "type": "timeseries",
   "description": "Кол-во неудачных запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Error - Response Code",
   "type": "timeseries",
   "description": "Кол-во неудачных запросов по кодам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/ AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"responseCode\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time - Failed (95th pct)",
   "type": "timeseries",
   "description": "Время выполнения неудачных запросов (95thpct)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS - 5xx",
   "type": "timeseries",
   "description": "Кол-во запросов в секунду с кодом ответа 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" =~ /5../ AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^HTTP.*/ AND \"responseCode\" =~ /5../) AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/5../" }
     ]
    }
   ]
  },
  {
   "title": "Pie - Error Response Code",
   "type": "piechart",
   "description": "Пирог с процентом ошибок по кодам",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_responseCode",
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/ AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"responseCode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" },
      { "condition": "AND", "key": "transaction::tag", "operator": "=~", "value": "/^$transaction$/" }
     ]
    }
   ]
  },
  {
   "title": "Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Info",
     "type": "table",
     "description": "Таблица с краткой информацией об ошибках",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" },
        { "params": [ "responseMessage" ], "type": "tag" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/) AND $timeFilter GROUP BY \"responseCode\", \"responseMessage\", \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
       ]
      }
     ]
    },
    {
     "title": "Error Info по HTTP*",
     "type": "table",
     "description": "Таблица с краткой информацией об ошибках",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "responseCode" ], "type": "tag" },
        { "params": [ "responseMessage" ], "type": "tag" },
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"responseCode\" !~ /^$/ AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"responseCode\", \"responseMessage\", \"transaction\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "responseCode", "operator": "!~", "value": "/^$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Transaction Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Transaction Table по _UC*",
   "type": "table",
   "description": "Таблица со статистикой запросов / транзакций",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") AS \"passReq\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "passReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") AS \"failReq\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "failReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") AS \"resTime95\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime95" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") AS \"resTime99\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")  / 5 AS \"rpsAvg\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 5" ], "type": "math" },
       { "params": [ "rpsAvg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT max(\"count\")  / 5 AS \"rpsMax\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" =~ /^_UC.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 5" ], "type": "math" },
       { "params": [ "rpsMax" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Table по HTTP*",
   "type": "table",
   "description": "Таблица со статистикой запросов / транзакций",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") AS \"passReq\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ok' AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "passReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") AS \"failReq\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"statut\" = 'ko' AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "failReq" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") AS \"resTime95\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime95" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") AS \"resTime99\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "resTime99" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")  / 5 AS \"rpsAvg\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 5" ], "type": "math" },
       { "params": [ "rpsAvg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT max(\"count\")  / 5 AS \"rpsMax\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 5" ], "type": "math" },
       { "params": [ "rpsMax" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Bytes по HTTP*",
     "type": "timeseries",
     "description": "Полученные байты",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"rb\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"rb\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "rb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      }
     ]
    },
    {
     "title": "Sent Bytes по HTTP*",
     "type": "timeseries",
     "description": "Отправленные байты",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "transaction" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"sb\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation), \"transaction\" fill(null)",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      },
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "1s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"sb\")  / 5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /^$application$/ AND \"transaction\" != 'all' AND \"transaction\" =~ /^HTTP.*/) AND $timeFilter GROUP BY time($aggregation) fill(null)",
       "select": [
        [
         { "params": [ "sb" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 5" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "application", "operator": "=~", "value": "/^$application$/" },
        { "condition": "AND", "key": "transaction", "operator": "!=", "value": "all" }
       ]
      }
     ]
    }
   ]
  }
 ]
}